version: "3"
services:
  firesquadxx_backend:
    container_name: firesquadxx_backend_container
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /backend/node_modules
    command: npm run dev
    ports:
      - 8000:8000
    restart: always

  firesquadxx_frontend:
    container_name: firesquadxx_frontend_container
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - 8001:8001
    restart: always
